import { IMatch, IPostDefault, IProfile, ICourse, INewPostDefault, IDefaults } from './interfaces'

export const demoMatches: IMatch[] = [
	{
        match_id: 0,
		matchStatus: 4,
        golfer_id: 1,
        firstName: "Andy",
        lastName: "Rocks",
        age: 22,
        phoneNum: '4125528397',
        compatibility: 78,
        handicap: 19,
        transport: 'Carting',
        isDrinking: true,
        isBetting: true,
        isMusic: true,
        numHoles: 18,
        numPeople: 4,
        image: require('../assets/Andy.jpg'),
    },
	{
        match_id: 0,
		matchStatus: 4,
        golfer_id: 2,
        firstName: "Timmy",
        lastName: "Gallagher",
        age: 22,
        phoneNum: '2158079609',
        compatibility: 98,
        handicap: 20,
        transport: 'Walking',
        isDrinking: false,
        isBetting: false,
        isMusic: false,
        numHoles: 9,
        numPeople: 2,
        image: require('../assets/Timmy.jpg'),
    },
	{
        match_id: 0,
		matchStatus: 3,
        golfer_id: 3,
        firstName: "Jae",
        lastName: "Chang",
        age: 22,
        phoneNum: '2489248556',
        compatibility: 80,
        handicap: 21,
        transport: 'Walking',
        isDrinking: true,
        isBetting: false,
        isMusic: false,
        numHoles: 9,
        numPeople: 4,
        image: require('../assets/Jae.png'),
    },
]

export const demoAcceptedMatches: IMatch[] = [
	{
        match_id: 0,
		matchStatus: 4,
        golfer_id: 1,
        firstName: "Andy",
        lastName: "Rocks",
        age: 22,
        phoneNum: '4125528397',
        compatibility: 78,
        handicap: 19,
        transport: 'Carting',
        isDrinking: true,
        isBetting: true,
        isMusic: true,
        numHoles: 18,
        numPeople: 4,
        image: require('../assets/Andy.jpg'),
    },
	{
        match_id: 0,
		matchStatus: 4,
        golfer_id: 2,
        firstName: "Timmy",
        lastName: "Gallagher",
        age: 22,
        phoneNum: '2158079609',
        compatibility: 98,
        handicap: 20,
        transport: 'Walking',
        isDrinking: false,
        isBetting: false,
        isMusic: false,
        numHoles: 9,
        numPeople: 2,
        image: require('../assets/Timmy.jpg'),
    }
]

export const demoPendingMatches: IMatch[] = [
	{
        match_id: 0,
		matchStatus: 3,
        golfer_id: 3,
        firstName: "Jae",
        lastName: "Chang",
        age: 22,
        phoneNum: '2489248556',
        compatibility: 80,
        handicap: 21,
        transport: 'Walking',
        isDrinking: true,
        isBetting: false,
        isMusic: false,
        numHoles: 9,
        numPeople: 4,
        image: require('../assets/Jae.png'),
    },
]

export const demoProfiles: IProfile[] = [
	{
		golfer_id: 0,
		firstName: "Ramzi",
		lastName: "Bualuan",
		age: 35,
        phoneNum: '574-631-7388',
		handicap: 20,
		transport: "Carting",
		isDrinking: true,
		numHoles: 18,
		numPeople: 4,
		profileStatus: 0,
		image: require('../assets/Ramzi.jpeg'),
	},
    {
        golfer_id: 1,
        firstName: "Andy",
        lastName: "Rocks",
        matchStatus: 4,
        age: 22,
        phoneNum: '4125528397',
        compatibility: 78,
        handicap: 19,
        transport: 'Carting',
        isDrinking: true,
        numHoles: 18,
        numPeople: 4,
        profileStatus: 1,
        image: require('../assets/Andy.jpg'),
    },
	{
        golfer_id: 2,
        firstName: "Timmy",
        lastName: "Gallagher",
        matchStatus: 4,
        age: 22,
        phoneNum: '2158079609',
        compatibility: 98,
        handicap: 20,
        transport: 'Walking',
        isDrinking: false,
        numHoles: 9,
        numPeople: 2,
        profileStatus: 1,
        image: require('../assets/Timmy.jpg'),
    },
	{
        golfer_id: 3,
        firstName: "Jae",
        lastName: "Chang",
        matchStatus: 3, 
        age: 22,
        phoneNum: '2489248556',
        compatibility: 80,
        handicap: 21,
        transport: 'Walking',
        isDrinking: true,
        numHoles: 9,
        numPeople: 4,
        profileStatus: 1,
        image: require('../assets/Jae.png'),
    },
];

export const demoPostDefaults: IPostDefault = {
    handicap: 21,
    transport: 'Walking',
    isDrinking: false,
    isBetting: false,
    isMusic: true,
    numPeople: 4,
    numHoles: 18,
}

export const demoCourses: ICourse[] = [
    {
        course_id: 0,
        courseName: 'Burke Golf Course',
        courseDescription: 'Designed as a regulation 18-hole course in 1929, the Burke Golf Course today consists of 9 holes in the picturesque setting of Notre Dame.',
        website: 'https://burkegolfcourse.nd.edu/',
        phoneNum: '(574) 631-6425',
        latitude: 41.6992406021,
        longitude: -86.2442565867,
        difficulty: 3,
    },
    {
        course_id: 1,
        courseName: 'Warren Golf Course',
        courseDescription: 'The Warren Golf Course at Notre Dame features 18 holes and is one of the best public golf courses in Indiana and the Midwest.',
        website: 'https://warrengolfcourse.com/',
        phoneNum: '(574) 631-4653',
        latitude: 41.7094940875, 
        longitude: -86.2224572846,
        difficulty: 5,
    },
    {
        course_id: 2,
        courseName: 'Morris Park Country Club Golf Course',
        courseDescription: 'Morris Park Country Club is a private country club located in South Bend, Indiana.',
        website: 'https://www.morrisparkcc.com/index.php',
        phoneNum: '(574) 233-9474',
        latitude: 41.680988624195244,  
        longitude: -86.21221530759207,
        difficulty: 4,
    },
    {
        course_id: 3,
        courseName: 'Studebaker Golf Course',
        courseDescription: 'Studebaker Golf Course is a historic golf course perfect for every level of golfer. A 9-hole bent grass greens and bluegrass/fescue course with water hazards in play. ',
        website: 'http://www.sbparkgolf.org/studebaker/',
        phoneNum: '(574) 287-6634',
        latitude: 41.65424782221799, 
        longitude: -86.24038255514074,
        difficulty: 4,
    },
    {
        course_id: 4,
        courseName: 'Blackthorn Golf Club',
        courseDescription: 'Upon its opening, Blackthorn was ranked the No. 4 best new public golf course by Golf Digest. While no longer a municipal course as of 2015, it was given the prestigious title of the No. 1 municipal course in Indiana and No. 44 in the country by Golf Week Magazine in 2013. Blackthorn was ranked a 5-star course by Chicagoland Golf, and it is among the top 100 women-friendly courses in the country.',
        website: 'http://blackthorngolf.com/',
        phoneNum: '(574) 232-4653',
        latitude: 41.72112940301731, 
        longitude: -86.33372964621513,
        difficulty: 4,
    },
    {
        course_id: 5,
        courseName: 'Juday Creek Golf Course',
        courseDescription: 'Juday Creek is an 18-Hole Championship Golf Course in Granger Indiana, minutes from The University of Notre Dame.',
        website: 'https://www.judaycreek.com/',
        phoneNum: '(574) 277-4653',
        latitude: 41.72097255681638, 
        longitude: -86.15397680210216,
        difficulty: 4,
    }
]